// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/about.tsx";
import * as $4 from "./routes/api/products/[id].ts";
import * as $5 from "./routes/api/products/index.ts";
import * as $6 from "./routes/demo.tsx";
import * as $7 from "./routes/github/[username].tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/products/[id].tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/about.tsx": $3,
    "./routes/api/products/[id].ts": $4,
    "./routes/api/products/index.ts": $5,
    "./routes/demo.tsx": $6,
    "./routes/github/[username].tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/products/[id].tsx": $9,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Counter.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
